/**
 * Provider Cockpit — tier-aligned combo suite with safeguards.
 *
 * Pure: turns a CockpitPayload into `createComboSchema`-shaped combo inputs.
 * Every generated combo is prefixed `cockpit-` and upserted by name, so
 * regeneration never touches hand-made combos. Apply order matters: the
 * universal combo references the use-case combos, so it is emitted last.
 */

import type { CapabilityTier } from "./tiers";
import type { CockpitModel, CockpitPayload, CockpitProvider } from "./aggregate";

export const COCKPIT_COMBO_PREFIX = "cockpit-";

export interface CockpitComboConfig {
  maxRetries: number;
  retryDelayMs: number;
  fallbackDelayMs: number;
  maxGlobalAttempts: number;
  targetTimeoutMs: number;
  healthCheckEnabled: boolean;
  trackMetrics: boolean;
  reasoningTokenBufferEnabled?: boolean;
  nestedComboMode?: "execute";
  maxComboDepth?: number;
}

export type CockpitComboStep =
  | { kind: "model"; providerId: string; model: string; allowedConnectionIds?: string[] }
  | { kind: "combo-ref"; comboName: string };

export interface CockpitCombo {
  name: string;
  description: string;
  strategy: "priority" | "p2c" | "round-robin";
  models: CockpitComboStep[];
  config: CockpitComboConfig;
}

const TIER_TIMEOUT_MS: Record<CapabilityTier, number> = { 1: 90_000, 2: 45_000, 3: 30_000 };
const DESCRIPTION =
  "Generated by the Provider Cockpit (/dashboard/provider-stats). Regenerate there instead of editing by hand.";

interface Candidate {
  provider: CockpitProvider;
  model: CockpitModel;
}

function usableProvider(p: CockpitProvider): boolean {
  return p.status !== "open" && p.status !== "down";
}

function eligibleCandidates(payload: CockpitPayload): Candidate[] {
  const out: Candidate[] = [];
  for (const provider of payload.providers) {
    if (!usableProvider(provider)) continue;
    for (const model of provider.models) {
      if (model.eligible) out.push({ provider, model });
    }
  }
  return out;
}

function capPerProvider(candidates: Candidate[], perProvider: number, total: number): Candidate[] {
  const counts = new Map<string, number>();
  const out: Candidate[] = [];
  for (const c of candidates) {
    const n = counts.get(c.provider.id) ?? 0;
    if (n >= perProvider) continue;
    counts.set(c.provider.id, n + 1);
    out.push(c);
    if (out.length >= total) break;
  }
  return out;
}

function modelStep(c: Candidate, scopeConnections = false): CockpitComboStep {
  const step: CockpitComboStep = {
    kind: "model",
    providerId: c.provider.id,
    model: `${c.provider.id}/${c.model.id}`,
  };
  if (
    scopeConnections &&
    c.provider.connections.total > 0 &&
    c.provider.usableConnectionIds.length
  ) {
    step.allowedConnectionIds = [...c.provider.usableConnectionIds].sort();
  }
  return step;
}

function safeguards(candidates: Candidate[]): CockpitComboConfig {
  const bestTier = candidates.reduce<CapabilityTier>(
    (t, c) => (c.model.tier < t ? c.model.tier : t),
    3
  );
  const config: CockpitComboConfig = {
    maxRetries: 1,
    retryDelayMs: 500,
    fallbackDelayMs: 250,
    maxGlobalAttempts: 12,
    targetTimeoutMs: TIER_TIMEOUT_MS[bestTier],
    healthCheckEnabled: true,
    trackMetrics: true,
  };
  if (candidates.some((c) => c.model.supportsReasoning)) config.reasoningTokenBufferEnabled = true;
  return config;
}

function build(
  name: string,
  strategy: CockpitCombo["strategy"],
  picked: Candidate[],
  scopeConnections = false
): CockpitCombo | null {
  if (picked.length === 0) return null;
  return {
    name,
    description: DESCRIPTION,
    strategy,
    models: picked.map((c) => modelStep(c, scopeConnections)),
    config: safeguards(picked),
  };
}

const byScore = (a: Candidate, b: Candidate) => b.model.score - a.model.score;
const latencyOf = (c: Candidate) =>
  c.model.p50Ms ?? c.model.avgLatencyMs ?? Number.POSITIVE_INFINITY;

function slug(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export function generateCockpitCombos(payload: CockpitPayload): CockpitCombo[] {
  const candidates = eligibleCandidates(payload);
  const combos: CockpitCombo[] = [];

  // A) use-case combos
  const flagship = build(
    `${COCKPIT_COMBO_PREFIX}flagship-coding`,
    "priority",
    capPerProvider(
      candidates.filter((c) => c.model.tier === 1 && c.model.toolCalling).sort(byScore),
      2,
      6
    )
  );
  const economy = build(
    `${COCKPIT_COMBO_PREFIX}fast-economy`,
    "p2c",
    capPerProvider(
      candidates
        .filter((c) => c.model.tier >= 2 && c.model.costTier !== "premium")
        .sort((a, b) => latencyOf(a) - latencyOf(b) || byScore(a, b)),
      2,
      8
    )
  );
  const free = build(
    `${COCKPIT_COMBO_PREFIX}free-unlimited`,
    "round-robin",
    capPerProvider(candidates.filter((c) => c.model.costTier === "free").sort(byScore), 3, 10)
  );
  for (const c of [flagship, economy, free]) if (c) combos.push(c);

  // B) per-provider resilience — only for providers with observed traffic in the
  // window, so the suite tracks what is actually in use (catalog-only providers
  // still feed the use-case combos above).
  for (const provider of payload.providers) {
    if (!usableProvider(provider) || provider.requests === 0) continue;
    const own = candidates
      .filter((c) => c.provider.id === provider.id)
      .sort((a, b) => a.model.tier - b.model.tier || byScore(a, b));
    const enough =
      own.length >= 2 || (own.length === 1 && provider.usableConnectionIds.length >= 2);
    if (!enough) continue;
    const combo = build(
      `${COCKPIT_COMBO_PREFIX}${slug(provider.id)}-resilient`,
      "priority",
      own.slice(0, 6),
      true
    );
    if (combo) combos.push(combo);
  }

  // C) universal safeguard: use-case combos in order, then the most stable free model.
  const refs = [flagship, economy, free].filter((c): c is CockpitCombo => c !== null);
  const lastResort = candidates
    .filter((c) => c.model.costTier === "free")
    .sort(
      (a, b) =>
        (b.model.requests >= 5 ? (b.model.successRate ?? 0) : 0) -
          (a.model.requests >= 5 ? (a.model.successRate ?? 0) : 0) || byScore(a, b)
    )[0];
  if (refs.length > 0) {
    const steps: CockpitComboStep[] = refs.map((c) => ({ kind: "combo-ref", comboName: c.name }));
    if (lastResort) steps.push(modelStep(lastResort));
    combos.push({
      name: `${COCKPIT_COMBO_PREFIX}universal-safeguard`,
      description: DESCRIPTION,
      strategy: "priority",
      models: steps,
      config: {
        ...safeguards(lastResort ? [lastResort] : []),
        targetTimeoutMs: TIER_TIMEOUT_MS[1],
        nestedComboMode: "execute",
        maxComboDepth: 3,
      },
    });
  }

  return combos;
}

// ── diff ────────────────────────────────────────────────────────────────────

export interface ExistingCombo {
  id: string;
  name: string;
  strategy?: string;
  models?: unknown[];
  config?: Record<string, unknown> | null;
}

export interface CockpitComboDiff {
  create: CockpitCombo[];
  update: Array<{ id: string; combo: CockpitCombo }>;
  unchanged: string[];
  /** Existing cockpit-* combos the current data no longer produces (reported, never deleted). */
  stale: string[];
}

function canonicalStep(step: unknown): string {
  if (typeof step === "string") return JSON.stringify({ kind: "model", model: step });
  const s = (step ?? {}) as Record<string, unknown>;
  if (s.kind === "combo-ref") return JSON.stringify({ kind: "combo-ref", comboName: s.comboName });
  const allowed = Array.isArray(s.allowedConnectionIds)
    ? [...(s.allowedConnectionIds as string[])].sort()
    : [];
  return JSON.stringify({ kind: "model", model: s.model, allowed });
}

function sameCombo(generated: CockpitCombo, existing: ExistingCombo): boolean {
  if ((existing.strategy || "priority") !== generated.strategy) return false;
  const a = generated.models.map(canonicalStep);
  const b = (existing.models ?? []).map(canonicalStep);
  if (a.length !== b.length || a.some((v, i) => v !== b[i])) return false;
  const cfg = existing.config ?? {};
  return Object.entries(generated.config).every(
    ([key, value]) => JSON.stringify(cfg[key]) === JSON.stringify(value)
  );
}

export function diffCockpitCombos(
  generated: CockpitCombo[],
  existing: ExistingCombo[]
): CockpitComboDiff {
  const existingByName = new Map(existing.map((c) => [c.name, c]));
  const diff: CockpitComboDiff = { create: [], update: [], unchanged: [], stale: [] };
  for (const combo of generated) {
    const current = existingByName.get(combo.name);
    if (!current) diff.create.push(combo);
    else if (sameCombo(combo, current)) diff.unchanged.push(combo.name);
    else diff.update.push({ id: current.id, combo });
  }
  const generatedNames = new Set(generated.map((c) => c.name));
  for (const c of existing) {
    if (c.name.startsWith(COCKPIT_COMBO_PREFIX) && !generatedNames.has(c.name)) {
      diff.stale.push(c.name);
    }
  }
  return diff;
}
